In [1]:
import numpy as np
import pandas as pd
import networkx as nx
from matplotlib import pyplot as plt




from pyvis.network import Network




In [152]:
df = pd.read_csv("actor_actor_pairs_movie_final.csv",header=None,names=['source','target','weight'])
df.head()

source              target  weight
0    Lionel Atwill     Morton Barteaux       1
1       David Sale     Johnny Lockwood       1
2           Ran Yi        Zhao Minglei       1
3  Gurie Sheffield     Kendall Gilmore       1
4  Goran Kovacevic  Jugoslav Kujundzic       1

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21565150 entries, 0 to 21565149
Data columns (total 3 columns):
 #   Column  Dtype 
---  ------  ----- 
 0   source  object
 1   target  object
 2   weight  int64 
dtypes: int64(1), object(2)
memory usage: 493.6+ MB


In [166]:
dftemp = pd.concat([df['source'],df['target']],ignore_index=True).value_counts()

KeyboardInterrupt: 

In [158]:
jkeep = 400
node_labels = dftemp[dftemp>jkeep].index

In [165]:
node_labels

Index(['William Shakespeare', 'Kevin MacLeod', 'Ron Jeremy', 'Tom Byron',
       'Mick Blue', 'Mark Davis', 'Sean Michaels', 'Erik Everhard',
       'Joey Silvera', 'Eric Roberts',
       ...
       'Lito Anzures', 'Blair Harris', 'Giorgos Triandafyllou', 'Mazhar Khan',
       'Alexander Hall', 'Axel Graatkjær', 'Matthias Fuchs',
       'Kenneth Cranham', 'Jung Jin-woo', 'Jeffrey Schenck'],
      dtype='object', length=6873)

In [160]:
num_node_labels = len(node_labels)
node_encoding = list(range(num_node_labels))

map_key = {node_labels[j]:node_encoding[j] for j in range(num_node_labels)}
df['source'] = df['source'].map(map_key)
df['target'] = df['target'].map(map_key)

In [162]:
df = df.dropna()

In [13]:
a = [[5,2,3],[3,4,5],[2,3,2]]
a[0].sort()
a

[[2, 3, 5], [3, 4, 5], [2, 3, 2]]

In [10]:
a

In [43]:
a = np.array([[1,2,3],[3,4,5],[2,3,2],[1,4,6]])
print(a)

print(np.sum(a, axis=1)) # sum across columns (return size is equal to num_rows)

print(np.mean(a, axis=1)) # mean across columns (return size is equal to num_rows)

print(np.sort(a, axis=1)) # sort across the columns (i.e. sort the individual rows)

print(np.sort(a, axis=0)) # sort across the rows (i.e. sort the individual columns)

print(np.sort(a, axis=None)) # flatten the array and then sort

[[1 2 3]
 [3 4 5]
 [2 3 2]
 [1 4 6]]
[ 6 12  7 11]
[2.         4.         2.33333333 3.66666667]
[[1 2 3]
 [3 4 5]
 [2 2 3]
 [1 4 6]]
[[1 2 2]
 [1 3 3]
 [2 4 5]
 [3 4 6]]
[1 1 2 2 2 3 3 3 4 4 5 6]


In [45]:
df = pd.DataFrame(a,columns=['a','b','c'])
print(df.head())
print()
print(df.sum(axis=1))
print()
print(df.mean(axis=1))
print()
print(df.sort_values(by=['a'],axis=0))
print()
print(df.apply(sum,axis=1))



   a  b  c
0  1  2  3
1  3  4  5
2  2  3  2
3  1  4  6

0     6
1    12
2     7
3    11
dtype: int64

0    2.000000
1    4.000000
2    2.333333
3    3.666667
dtype: float64

   a  b  c
0  1  2  3
3  1  4  6
2  2  3  2
1  3  4  5

0     6
1    12
2     7
3    11
dtype: int64


In [163]:
# compute size of nodes based on number of connections
node_size = []
for jactor in node_encoding:
    actor_weight = df[(df['target'] == jactor) | (df['source'] == jactor)]['weight']
    node_size.append(len(actor_weight)*np.sum(actor_weight))
node_size = 20*np.array(node_size)/np.max(node_size)

In [164]:
net = Network(notebook=True,cdn_resources='remote',bgcolor='#222222',font_color='white',height='750px',width='100%',select_menu=True,filter_menu=True)
net.add_nodes(node_encoding,label=node_labels,size=node_size)
net.add_edges(edges)
net.repulsion(node_distance=200, spring_length=2)
net.show_buttons()
net.show("actors_network.html");

actors_network.html


In [ ]:
# example of network taken from Medium post
# net = Network(notebook=True,cdn_resources='remote',bgcolor='#222222',font_color='white',height='750px',width='100%',select_menu=True,filter_menu=True)
# net.add_nodes([0,1],label=['Alex','Carthy'])
# net.add_edges([(0,1,10)])
# net.repulsion(node_distance=100, spring_length=20)
# net.show_buttons()
# net.show("list_of_nodes.html");